example for milling of a logo
WBK-Robotics/pybullet_industrial pull request #32
Opened 2022-09-01 17:04 UTC by koeri246

## Description
Millingpaths are being created based on the coordinates of the wbk-logo. An extruder follows the paths while removing voxels.

## Motivation and Context
Giving an example for milling as a possible introduction to the library.

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-09-01 17:08 UTC, koeri246 commented
- The robot has some issue following the paths of the "b" and "k" letter of the logo. The extruder does not follow these two paths properly, but undergoes a translation. But if only these two paths are created, the extruder follows them well.
- Further work is needed to make the extruder mill the inside of the letters too.

2022-09-01 19:55 UTC, liquidcronos requested changes

2022-09-01 19:55 UTC, liquidcronos commented on examples/pybullet_industrial_intro.py
> +def build_smaller_paths(path, scale):
This function is currently not used and should be deleted

2022-09-01 19:55 UTC, liquidcronos commented on examples/pybullet_industrial_intro.py
> +    p.setAdditionalSearchPath(pybullet_data.getDataPath())
While the monastery looks nice it does not realy work with the wbk branding and should be removed

2022-09-01 19:55 UTC, liquidcronos commented on examples/pybullet_industrial_intro.py
> +    p.configureDebugVisualizer(p.COV_ENABLE_RENDERING, 0)
disabling the rending before spawning the robot will make the simulation load even faster.
It therefore should be moved to line 124

2022-09-01 19:55 UTC, liquidcronos commented on examples/pybullet_industrial_intro.py
> +    while i<len(x_data):
while loops should be used with caution since they can run endlessly, consider using a for loop if possible.

2022-09-01 19:55 UTC, liquidcronos commented on examples/pybullet_industrial_intro.py
> +    while i<len(path_list):
while loops should be used with caution since they can run endlessly, consider using a for loop if possible.

2022-09-11 11:15 UTC, liquidcronos approved these changes

2022-09-11 11:15 UTC, merged